subjects = {'g': {'Физика': {'Общая физика': {'Семестр 1': '+++',
                                                    'Семестр 2': '+++',
                                                    'Семестр 3': '+++',
                                                    'Семестр 4': '+++'
                                                    },
                                   'Электродинамика': '+--',
                                   'Теор механика': {'Семестр 3': '---',
                                                     'Семестр 4': '---'

                                                     },
                                   'Мат физика': '---',
                                   'Физ химия': '---',
                                   'Квант механика': '---',
                                   'Теория упругости': '---',
                                   'Численные методы': '---',
                                   'Лаб работы': '---'},
                        'Математика': {'Диф уравнения': '---',
                                       'Мат анализ': {'Семестр 1': '+++',
                                                      'Семестр 2': '+++',
                                                      'Семестр 3': '+++'
                                                      },
                                       'Теор вероятностей': '---',
                                       'Лин алгебра': {'Семестр 1': '++-',
                                                            'Семестр 2': '++-',
                                                            'Семестр 3': '++-'
                                                            },
                                       'Компл анализ': '---',
                                       'Теория групп': '---',
                                       'Топология': '---'},
                        'Языки': {'Китайский': '---',
                                  'Немецкий': '---',
                                  'Испанский': '---',
                                  'Английский': '---'},
                        'История России': {'Рус культура': '---',
                                           'Наука и техника': '---',
                                           'Соц история ': '---',
                                           'Россия и мир': '---',
                                           'Россия в МО': '---',
                                           'РР в России': '---'},
                        'Программирование': {'Лекции по проге': '---',
                                             'Алгоритмы': '---',
                                             'Физ моделирование': '---',
                                             'Хранение и обработка данных': '---',
                                             'Машинное обучение': '---'},
                        'Физкультура': '---',
                        'ОБЖ': '---',
                        'Философия': '---'}}

info = {
    'g.Физика.Общая физика.Семестр 1': {
        'lections': 'https://www.youtube.com/playlist?list=PLIWWD4hFxKhNQhYtDq_lyBA9bz2opD-xp',
        'textbooks': ['./belchenko_mechanics.pdf','./kirichenko_mechanics.pdf','./kudlis_konspect.pdf'],
        'solvers': ['./ovckinkin2013.pdf','./silagadze.pdf'],},
    'g.Физика.Общая физика.Семестр 2': {
        'lections': 'https://vk.com/away.php?to=https%3A%2F%2Fwww.youtube.com%2Fplaylist%3Flist%3DPLIWWD4hFxKhO1q3bNGEuxWG-cXqJ0nr2a&cc_key=',
        'textbooks': ['./Kirichenko_therma.pdf','./sivuhin.pdf'],
        'solvers': ['./ovchinkin2013.pdf','./koryavov.pdf']},
'g.Физика.Общая физика.Семестр 3': {
        'lections': 'https://www.youtube.com/playlist?list=PLIWWD4hFxKhPwnMP0D7K72x17EsfzNUDa',
        'textbooks': ['./kirichenko_electricity.pdf','./sivuhin_electricity.pdf'],
        'solvers': ['./ovchinkin_electricity.pdf']},
'g.Физика.Общая физика.Семестр 4': {
        'lections': 'https://www.youtube.com/playlist?list=PLzMmAktiHfMJPT3uRZjS4ITaU3lwyxun4',
        'textbooks': ['./kirichenko_optic.djvu','./books/sivuhin_optic.pdf'],
        'solvers': ['./ovchinkin_electricity.pdf']},
'g.Физика.Электродинамика':{'lections': 'https://www.youtube.com/playlist?list=PLzMmAktiHfMJ7Y5Ed4G-JggSDqm70XBUa',
        'textbooks': [],
        'solvers': []},
'g.Физика.Теор механика.Семестр 3':{'lections': 'https://www.youtube.com/watch?v=OywfVtui_M0&list=PLzMmAktiHfMJFUudsSN2rLDvqzpcg0o_r&t=577s',
        'textbooks': [],
        'solvers': []},
'g.Физика.Теор механика.Семестр 4':{'lections': 'https://www.youtube.com/playlist?list=PLzMmAktiHfMJf84rK-ShQnoZpq7ao9RTn',
        'textbooks': ['./sivuhin_optic.pdf'],
        'solvers': './ovckinkin_mechanics_and_thermodynamics.pdf'},
    'g.Физика.Мат физика':{'lections': 'https://www.youtube.com/playlist?list=PLzMmAktiHfMIGz0KQFWbPkVhMgYLqPiki',
        'textbooks': './belchenko_mechanics.pdf',
        'solvers': './ovckinkin_mechanics_and_thermodynamics.pdf'},
'g.Физика.Физ химия':{'lections': 'https://www.youtube.com/playlist?list=PLzMmAktiHfMIIn1vUOuMU-mvlD_NnkCNu',
        'textbooks': ['./Korolev.pdf'],
        'solvers': []},
'g.Математика.Диф уравнения':{'lections': 'https://www.youtube.com/playlist?list=PL1Bg2H0GvcuzBu9jT1fjmCAmEUuGZvc1x',
        'textbooks': [],
        'solvers': []},
'g.Математика.Мат анализ.Семестр 1':{'lections': 'https://youtube.com/playlist?list=PLIWWD4hFxKhPiJSlpFNuekFOhvjU-0K5I&si=XvN-uryYIxgU72L_',
        'textbooks': ['./zorich_1st.pdf'],
        'solvers': ['./kudravciev.djvu','./demidovich.djvu']},
'g.Математика.Мат анализ.Семестр 2':{'lections': 'https://www.youtube.com/playlist?list=PLIWWD4hFxKhO9S1vsaUqmRZ-w0pjVeBaw',
        'textbooks': ['./zorich_1st.pdf','./zorich_2nd.pdf'],
        'solvers': ['./kudravciev2.djvu','./demidovich.djvu']},
'g.Математика.Мат анализ.Семестр 3':{'lections': 'https://www.youtube.com/playlist?list=PLzMmAktiHfMJ9gvLkAsTemCJ3UqCIthQU',
        'textbooks': ['./zorich_1st.pdf','./zorich_2nd.pdf'],
        'solvers': ['./kudravciev3.djvu','./demidovich.djvu']},
'g.Математика.Теор вероятностей':{'lections': 'https://www.youtube.com/playlist?list=PLgmkKrWm48R-61mb4JUITtGDNwSL3MUQH',
        'textbooks': [],
        'solvers': []},
'g.Математика.Лин алгебра.Семестр 1':{'lections':  'https://youtube.com/playlist?list=PLd7QXkfmSY7aNScUfSoi4RT0xvHdsrDWs&si=SvOnt8630gNR2qvw',
        'textbooks': ['./Vinberg.pdf','./Algebra_konspect.pdf','./linear_spaces.pdf'],
        'solvers': []},
'g.Математика.Лин алгебра.Семестр 2':{'lections': 'https://youtube.com/playlist?list=PLd7QXkfmSY7bD4Ok4_YpwZHPaFtM4F7dW&si=EQ3t0oFbddXwqjVx',
        'textbooks': ['./Vinberg.pdf','./tensor_algebra.pdf','./linear_operator.pdf','./evklidian_structure.pdf'],
        'solvers': []},
'g.Математика.Лин алгебра.Семестр 3':{'lections': 'https://www.youtube.com/playlist?list=PLd7QXkfmSY7YTGYjW0VorQag4N_n5Y6Nm',
        'textbooks': ['./Vinberg.pdf'],
        'solvers': []},

'g.Математика.Компл анализ':{'lections': 'https://www.youtube.com/playlist?list=PLzMmAktiHfML7Q3htVqqFXFeWCmpFa495',
        'textbooks': [],
        'solvers': []},
}
